"""initial

Revision ID: a46af76e7054
Revises: 
Create Date: 2026-05-14 09:43:53.426178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a46af76e7054'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('codigo_expediente', sa.String(length=20), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('dpi', sa.String(length=13), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.Enum('M', 'F', name='sexo'), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_codigo_expediente'), 'pacientes', ['codigo_expediente'], unique=True)
    op.create_index(op.f('ix_pacientes_dpi'), 'pacientes', ['dpi'], unique=True)
    op.create_index(op.f('ix_pacientes_nombre_completo'), 'pacientes', ['nombre_completo'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'MEDICO', 'RECEPCIONISTA', name='rol'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('medicos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=False),
    sa.Column('num_colegiado', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_medicos_num_colegiado'), 'medicos', ['num_colegiado'], unique=True)
    op.create_table('citas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paciente_id', sa.String(length=36), nullable=False),
    sa.Column('medico_id', sa.String(length=36), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.Enum('PROGRAMADA', 'CANCELADA', 'COMPLETADA', name='estadocita'), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_citas_medico_fecha', 'citas', ['medico_id', 'fecha_hora'], unique=False)
    op.create_table('consultas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cita_id', sa.String(length=36), nullable=False),
    sa.Column('diagnostico', sa.Text(), nullable=False),
    sa.Column('notas_clinicas', sa.Text(), nullable=True),
    sa.Column('plan_tratamiento', sa.Text(), nullable=True),
    sa.Column('fecha_consulta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cita_id'], ['citas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultas_cita_id'), 'consultas', ['cita_id'], unique=True)
    op.create_table('recetas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('consulta_id', sa.String(length=36), nullable=False),
    sa.Column('fecha_emision', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recetas_consulta_id'), 'recetas', ['consulta_id'], unique=False)
    op.create_table('signos_vitales',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('consulta_id', sa.String(length=36), nullable=False),
    sa.Column('presion_arterial', sa.String(length=20), nullable=True),
    sa.Column('temperatura', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('frecuencia_cardiaca', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('talla', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('imc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consulta_id')
    )
    op.create_table('medicamentos_receta',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('receta_id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('dosis', sa.String(length=50), nullable=True),
    sa.Column('via', sa.String(length=50), nullable=True),
    sa.Column('frecuencia', sa.String(length=50), nullable=True),
    sa.Column('duracion', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicamentos_receta_receta_id'), 'medicamentos_receta', ['receta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicamentos_receta_receta_id'), table_name='medicamentos_receta')
    op.drop_table('medicamentos_receta')
    op.drop_table('signos_vitales')
    op.drop_index(op.f('ix_recetas_consulta_id'), table_name='recetas')
    op.drop_table('recetas')
    op.drop_index(op.f('ix_consultas_cita_id'), table_name='consultas')
    op.drop_table('consultas')
    op.drop_index('ix_citas_medico_fecha', table_name='citas')
    op.drop_table('citas')
    op.drop_index(op.f('ix_medicos_num_colegiado'), table_name='medicos')
    op.drop_table('medicos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_pacientes_nombre_completo'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_dpi'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_codigo_expediente'), table_name='pacientes')
    op.drop_table('pacientes')
    # ### end Alembic commands ###
